import XCTest
import State

class TemplateTests: Test {
    
    func testEncodingAndDecodingAutoGeneratedModel() {
        var company = Company(name: "State llc",yearFounded: 2015, phoneNumber: "888-888-8888",  employees: [Employee]())
        let employee = Employee(name:"Joe", title: "CEO")
        company.employees?.append(employee)
        _ = company.write(to: tempURLFor("company.plist"), format: .plist)
        let testCompany = Company(file: tempURLFor("company.plist"), format: .plist)
        
        XCTAssert(testCompany != nil)
        XCTAssert(testCompany?.name == "State llc")
        XCTAssert(testCompany?.phoneNumber == "888-888-8888")
        XCTAssert(testCompany?.yearFounded == 2015)
        XCTAssert(testCompany?.employees?.count == 1)
        XCTAssert(testCompany?.employees?[0].name == "Joe")
    }
    
    func testTypes() {
        let test_out = TestTypes()
        _ = test_out.write(to: tempURLFor("test_types.plist"), format: .binary)
        let sut = TestTypes(file: tempURLFor("test_types.plist"), format: .binary)
        XCTAssert(sut != nil)
        XCTAssert(sut?.myBinary != nil)
        XCTAssert(sut?.myDate != nil)
        XCTAssert(sut?.myFloat == 4.567)
        XCTAssert(sut?.myDouble == -0.02)
        XCTAssert(sut?.myInt == 5)
        XCTAssert(sut?.myString == "Hello World")
        XCTAssert(sut?.myDecimal == 3.14)
    }
    
    func testImmutableTypes() {
        let test_out = TestImmutableTypes()
        _ = test_out.write(to: tempURLFor("test_immutable_types.plist"), format: .binary)
        let sut = TestImmutableTypes(file: tempURLFor("test_immutable_types.plist"), format: .binary)
        XCTAssert(sut != nil)
        XCTAssert(sut?.myBinary != nil)
        XCTAssert(sut?.myDate != nil)
        XCTAssert(sut?.myFloat == 4.567)
        XCTAssert(sut?.myDouble == -0.02)
        XCTAssert(sut?.myInt == 5)
        XCTAssert(sut?.myString == "Hello World")
        XCTAssert(sut?.myDecimal == 3.14)
    }

    func testOptionalTypes() {
        let test_out = TestOptionalTypes.CreateTestInstance()
        _ = test_out.write(to: tempURLFor("test_optional_types.plist"), format: .binary)
        let sut =  TestOptionalTypes(file: tempURLFor("test_optional_types.plist"), format: .binary)
        XCTAssert(sut != nil)
        XCTAssert(sut?.myBinary != nil)
        XCTAssert(sut?.myDate != nil)
        XCTAssert(sut?.myFloat == 4.567)
        XCTAssert(sut?.myDouble == -0.02)
        XCTAssert(sut?.myInt == 5)
        XCTAssert(sut?.myString == "Hello World")
        XCTAssert(sut?.myDecimal == 3.14)
    }
    
    func testImmutableOptionalTypes() {
        let test_out = TestImmutableOptionalTypes()
        _ = test_out.write(to: tempURLFor("test_immutable_optional_types.plist"), format: .binary)
        let sut = TestImmutableOptionalTypes(file: tempURLFor("test_immutable_optional_types.plist"), format: .binary)
        XCTAssert(sut != nil)
        XCTAssert(sut?.myBinary != nil)
        XCTAssert(sut?.myDate != nil)
        XCTAssert(sut?.myFloat == 4.567)
        XCTAssert(sut?.myDouble == -0.02)
        XCTAssert(sut?.myInt == 5)
        XCTAssert(sut?.myString == "Hello World")
        XCTAssert(sut?.myDecimal == 3.14)
    }

    func testCollections() {
        var test_out = TestCollections()
        test_out.arrayOfStrings = ["string1", "string2", "string3"]
        test_out.dicOfInts["int1"] = 1
        test_out.dicOfInts["int2"] = 2
        test_out.dicOfInts["int3"] = 3
        test_out.setOfStrings = ["do", "ray", "me"]
        _ = test_out.write(to: tempURLFor("test_collections.plist"), format: .binary)
        let sut =  TestCollections(file: tempURLFor("test_collections.plist"), format: .binary)
        
        XCTAssert(sut != nil)
        XCTAssert(sut?.arrayOfStrings.count == 3)
        XCTAssert(sut?.dicOfInts.count == 3)
        XCTAssert(sut?.setOfStrings.count == 3)
    }
    
    func testRawEnum() {
        let test_out = TestRawEnum.ready
        _ = test_out.write(to: tempURLFor("test_enum.plist"), format: .plist)
        let sut = TestRawEnum(file: tempURLFor("test_enum.plist"), format: .plist)
        XCTAssert(sut != nil)
        XCTAssert(sut == TestRawEnum.ready)
    }
    
    func testTransformable() {
        let test_out = TestTransformable( myTransformable: URL(string: "http://facebook.com")!, myTransformableImmutable: URL(string: "http://yahoo.com")!, myTransformableImmutableOptional: nil, myTransformableOptional:URL(string: "http://twitter.com")!)
        _ = test_out.write(to: tempURLFor("test_transformable.plist"), format: .binary)
        let sut =  TestTransformable(file: tempURLFor("test_transformable.plist"), format: .binary)
        XCTAssert(sut != nil)
        XCTAssert(sut?.myTransformable == test_out.myTransformable)
        XCTAssert(sut?.myTransformableImmutable == test_out.myTransformableImmutable)
        XCTAssert(sut?.myTransformableImmutableOptional == test_out.myTransformableImmutableOptional)
        XCTAssert(sut?.myTransformableOptional == test_out.myTransformableOptional)
    }
    
    func testOverrideType() {
        let test_out: TestOverrideType? = TestOverrideType(myURL: URL(string: "http://simpletouchsoftware.com"), myArrayOfString: ["string1", "string2"])
        XCTAssert(test_out != nil)
    }
}
