import XCTest
import Spot

class TemplateTests: Test {
    
    func testEncodingAndDecodingAutoGeneratedModel() {
        var company = Company(name: "Spot llc", phoneNumber: "888-888-8888", yearFounded: 2015, employees: [Employee]())
        let employee = Employee(name:"Joe", title: "CEO")
        company.employees?.append(employee)
        let data = Encoder.encode(company)
        Plist.write(data, path: tempPathFor("company.plist"))
        let testCompany: Company? = Decoder.decode(Plist.read(tempPathFor("company.plist")))
        
        XCTAssert(testCompany != nil)
        XCTAssert(testCompany?.name == "Spot llc")
        XCTAssert(testCompany?.phoneNumber == "888-888-8888")
        XCTAssert(testCompany?.yearFounded == 2015)
        XCTAssert(testCompany?.employees?.count == 1)
        XCTAssert(testCompany?.employees?[0].name == "Joe")
    }
}